require_relative 'commands/help'
require_relative 'commands/add_user'
require_relative 'commands/add_question'
require_relative 'commands/schedule_question'
require_relative 'commands/answer_question'
