default: &default
  adapter:  postgresql
  encoding: unicode
  host:     <%= Figaro.env.db_host %>
  user:     <%= Figaro.env.db_user %>
  password: <%= Figaro.env.db_password %>
  pool:     <%= Figaro.env.db_pool %>
  database: <%= Figaro.env.db_name %>
  timeout:  5000

development:
  <<: *default
  database: <%= Figaro.env.db_name %>_dev

test:
  <<: *default
  database: <%= Figaro.env.db_name %>_test

production:
  <<: *default
  database: <%= Figaro.env.db_name %>
